Test single version of nightly

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -43,8 +43,10 @@ jobs:
         tf-version: ['2.1.0', '2.2.0rc2']
       fail-fast: false
     steps:
-      - if: github.event_name == 'push'
-        run: echo "::set-env name=NIGHTLY_FLAG::--nightly"
+      - if: github.event_name == 'pull_request'
+        run: |
+          echo "::set-env name=NIGHTLY_FLAG::--nightly"
+          python -m pip install GitPython
       - uses: actions/checkout@v2
       - uses: actions/setup-python@v1
         with:
@@ -107,28 +109,28 @@ jobs:
           pip install wheel/*.whl
           python -c "import tensorflow_addons as tfa; print(tfa.activations.lisht(0.2))"
 
-  upload-wheels:
-    name: Publish wheels to PyPi
-    needs: [release-wheel, test-release-wheel, test-with-bazel]
-    runs-on: ubuntu-18.04
-    strategy:
-      matrix:
-        os: ['macOS', 'Windows', 'Linux']
-        py-version: ['3.5', '3.6', '3.7']
-      fail-fast: false
-    steps:
-      - uses: actions/download-artifact@v1
-        if: github.event_name != 'pull_request' || matrix.py-version == env.OLDEST_PY_VERSION
-        with:
-          name: ${{ runner.os }}-${{ matrix.py-version }}-tf2.1.0-wheel
-          path: ./dist
-      - if: github.event_name != 'pull_request' || matrix.py-version == env.OLDEST_PY_VERSION
-        run: |
-          set -e -x
-          ls -la dist/
-          sha256sum dist/*.whl
-      - uses: pypa/gh-action-pypi-publish@v1.1.0
-        if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'release'
-        with:
-          user: __token__
-          password: ${{ secrets.pypi_token }}
+#  upload-wheels:
+#    name: Publish wheels to PyPi
+#    needs: [release-wheel, test-release-wheel, test-with-bazel]
+#    runs-on: ubuntu-18.04
+#    strategy:
+#      matrix:
+#        os: ['macOS', 'Windows', 'Linux']
+#        py-version: ['3.5', '3.6', '3.7']
+#      fail-fast: false
+#    steps:
+#      - uses: actions/download-artifact@v1
+#        if: github.event_name != 'pull_request' || matrix.py-version == env.OLDEST_PY_VERSION
+#        with:
+#          name: ${{ runner.os }}-${{ matrix.py-version }}-tf2.1.0-wheel
+#          path: ./dist
+#      - if: github.event_name != 'pull_request' || matrix.py-version == env.OLDEST_PY_VERSION
+#        run: |
+#          set -e -x
+#          ls -la dist/
+#          sha256sum dist/*.whl
+#      - uses: pypa/gh-action-pypi-publish@v1.1.0
+#        if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'release'
+#        with:
+#          user: __token__
+#          password: ${{ secrets.pypi_token }}
